name: Test Project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Get the Code
      uses: actions/checkout@v3
    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install Dependencies
      run: npm ci
    - name: Run the Tests
      run: npm run test